// MobileRobotSimulator.cpp

#include "stdafx.h"
#include "MobileRobotSimulator.h"
#include "MobileRobotSimulatorDlg.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif

// CMobileRobotSimulatorApp

BEGIN_MESSAGE_MAP(CMobileRobotSimulatorApp, CWinApp)
	ON_COMMAND(ID_HELP, &CWinApp::OnHelp)
END_MESSAGE_MAP()

//CMobileRobotSimulatorApp
CMobileRobotSimulatorApp theApp;

BOOL CMobileRobotSimulatorApp::InitInstance()
{
	// The application manifest uses ComCtl32.dll version 6 or later to create a visual style
	// If you specify to use, InitCommonControlsEx () is required on Windows XP.
	// You can not create a window unless InitCommonControlsEx () is used.
	INITCOMMONCONTROLSEX InitCtrls;
	InitCtrls.dwSize = sizeof(InitCtrls);
	// to include all the common control classes to be used by the application
	// Set this item.
	InitCtrls.dwICC = ICC_WIN95_CLASSES;
	InitCommonControlsEx(&InitCtrls);

	CWinApp::InitInstance();

	if (!AfxSocketInit())
	{
		AfxMessageBox(IDP_SOCKETS_INIT_FAILED);
		return FALSE;
	}

	AfxEnableControlContainer();

	// standard initialization
	// To reduce the size of the final executable without using these features
	// specific initialization not needed below
	// routines should be removed.
	// Change the registry key where the settings are stored.
	// You need to modify it with the appropriate content.
	SetRegistryKey(_T("Applications generated by the Local Application Wizard"));

	CMobileRobotSimulatorDlg dlg;
	m_pMainWnd = &dlg;
	INT_PTR nResponse = dlg.DoModal();
	if (nResponse == IDOK)
	{
		// TODO: Click OK here to process when the dialog disappears
		// Place the code.
	}
	else if (nResponse == IDCANCEL)
	{
		// TODO: Click [Cancel] here to process when dialog disappears
		// Place the code.
	}

	// FALSE to allow the application to exit without starting the application's message pump because the dialog is closed
	// returns.
	return FALSE;
}
